version: "3.4"

x-logging: &default-logging
  options:
    max-size: "200k"
    max-file: "10"

services:
  api:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - ".env"
    environment:
      - HTTP_HOST=0.0.0.0
      - NODE_ENV=production
    depends_on:
      - pg
      - redis
    links:
      - pg
      - redis
    restart: unless-stopped
    logging: *default-logging
  pg:
    image: mdillon/postgis
    env_file:
      - ".env"
    ports:
      - 6543:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    logging: *default-logging
  redis:
    image: bitnami/redis
    env_file:
      - ".env"
    ports:
      - 6379:6379
    volumes:
      - redisdata:/bitnami/redis/data
    logging: *default-logging
volumes:
  pgdata:
  redisdata:
