version: "3.3"
services:
  api:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - ".env"
    environment:
      - HTTP_HOST=0.0.0.0
    depends_on:
      - postgis
    links:
      - postgis
    restart: unless-stopped
  postgis:
    image: mdillon/postgis
    env_file:
      - ".env"
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
